[PHP]
extension_dir="C:\Users\Lenovo\AppData\Local\Programs\Local\resources\extraResources\lightning-services\php-8.2.29+0\bin\win64\ext"

; Extensions needed for wp-cli
extension=php_curl.dll
extension=php_gettext.dll
extension=php_openssl.dll
extension=php_exif.dll
extension=php_gd.dll
extension=php_ftp.dll
extension=php_ffi.dll
extension=php_bz2.dll
extension=php_mbstring.dll
extension=php_sodium.dll
extension=php_tidy.dll
extension=php_xsl.dll
extension=php_soap.dll
extension=php_mysqli.dll
extension=php_pdo_mysql.dll
extension=php_fileinfo.dll
extension=php_pdo_sqlite.dll
extension=php_sqlite3.dll
extension=php_zip.dll
extension=php_intl.dll

; Limits
max_execution_time = 1200
memory_limit = 256M
post_max_size = 1000M
upload_max_filesize = 300M
max_file_uploads = 20
max_input_vars = 4000

; Error handling
error_reporting = E_ALL & ~E_DEPRECATED
display_errors = On
log_errors = On

; Other
short_open_tag = On
default_charset = "UTF-8"
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60
file_uploads = On
date.timezone = UTC
openssl.cafile="C:\Users\Lenovo\AppData\Local\Programs\Local\resources\extraResources\lightning-services\php-8.2.29+0\bin\win64\cacert.pem"

[MySQLi]
mysqli.default_port = 3306

[Pdo_Mysql]
pdo_mysql.default_port = 3306
